import { Recipe } from '@core/models/recipe.model';

export const MockRundomRecipes: Recipe[] = [
    {
      vegetarian: false,
      vegan: false,
      glutenFree: true,
      dairyFree: true,
      veryHealthy: false,
      cheap: false,
      veryPopular: false,
      sustainable: false,
      weightWatcherSmartPoints: 17,
      gaps: 'no',
      lowFodmap: false,
      aggregateLikes: 6,
      spoonacularScore: 74,
      healthScore: 31,
      creditsText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
      license: 'CC BY 3.0',
      sourceName: 'Foodista',
      pricePerServing: 636.03,
      extendedIngredients: [
        {
          id: 15270,
          aisle: 'Seafood',
          image: 'shrimp.png',
          consistency: 'solid',
          name: 'shrimp',
          nameClean: 'shrimp',
          original: '2 pounds large shrimp, shelled and deveined',
          originalName: 'shrimp, shelled and deveined',
          amount: 2,
          unit: 'pounds',
          meta: ['shelled', 'deveined'],
          measures: {
            us: {
              amount: 2,
              unitShort: 'lb',
              unitLong: 'pounds',
            },
            metric: {
              amount: 907.185,
              unitShort: 'g',
              unitLong: 'grams',
            },
          },
        },
        {
          id: 9037,
          aisle: 'Produce',
          image: 'avocado.jpg',
          consistency: 'solid',
          name: 'hass avocados',
          nameClean: 'avocado',
          original: '2 Hass avocados, pitted, peeled & cubed',
          originalName: 'Hass avocados, pitted, peeled & cubed',
          amount: 2,
          unit: '',
          meta: ['pitted', 'cubed', 'peeled'],
          measures: {
            us: {
              amount: 2,
              unitShort: '',
              unitLong: '',
            },
            metric: {
              amount: 2,
              unitShort: '',
              unitLong: '',
            },
          },
        },
        {
          id: 9176,
          aisle: 'Produce',
          image: 'mango.jpg',
          consistency: 'solid',
          name: 'mango',
          nameClean: 'mango',
          original: '1 mango, peeled and diced',
          originalName: 'mango, peeled and diced',
          amount: 1,
          unit: '',
          meta: ['diced', 'peeled'],
          measures: {
            us: {
              amount: 1,
              unitShort: '',
              unitLong: '',
            },
            metric: {
              amount: 1,
              unitShort: '',
              unitLong: '',
            },
          },
        },
        {
          id: 1029159,
          aisle: 'Produce',
          image: 'lime-wedge.jpg',
          consistency: 'solid',
          name: 'lime wedges',
          nameClean: 'lime wedge',
          original: 'Lime wedges, for serving',
          originalName: 'Lime wedges, for serving',
          amount: 1,
          unit: 'serving',
          meta: ['for serving'],
          measures: {
            us: {
              amount: 1,
              unitShort: 'serving',
              unitLong: 'serving',
            },
            metric: {
              amount: 1,
              unitShort: 'serving',
              unitLong: 'serving',
            },
          },
        },
        {
          id: 9176,
          aisle: 'Produce',
          image: 'mango.jpg',
          consistency: 'solid',
          name: 'mango',
          nameClean: 'mango',
          original: '1 mango, peeled and finely diced (1 1/2 cups)',
          originalName: 'mango, peeled and finely diced',
          amount: 1.5,
          unit: 'cups',
          meta: ['diced', 'peeled', 'finely'],
          measures: {
            us: {
              amount: 1.5,
              unitShort: 'cups',
              unitLong: 'cups',
            },
            metric: {
              amount: 354.882,
              unitShort: 'ml',
              unitLong: 'milliliters',
            },
          },
        },
        {
          id: 1022068,
          aisle: 'Oil, Vinegar, Salad Dressing',
          image: 'red-wine-vinegar.jpg',
          consistency: 'liquid',
          name: 'red wine vinegar',
          nameClean: 'red wine vinegar',
          original: '1/4 cup red wine vinegar',
          originalName: 'red wine vinegar',
          amount: 0.25,
          unit: 'cup',
          meta: ['red'],
          measures: {
            us: {
              amount: 0.25,
              unitShort: 'cups',
              unitLong: 'cups',
            },
            metric: {
              amount: 59.147,
              unitShort: 'ml',
              unitLong: 'milliliters',
            },
          },
        },
        {
          id: 9160,
          aisle: 'Produce',
          image: 'lime-juice.png',
          consistency: 'liquid',
          name: 'lime juice',
          nameClean: 'lime juice',
          original: '2 tablespoons fresh lime juice',
          originalName: 'fresh lime juice',
          amount: 2,
          unit: 'tablespoons',
          meta: ['fresh'],
          measures: {
            us: {
              amount: 2,
              unitShort: 'Tbsps',
              unitLong: 'Tbsps',
            },
            metric: {
              amount: 2,
              unitShort: 'Tbsps',
              unitLong: 'Tbsps',
            },
          },
        },
        {
          id: 11216,
          aisle: 'Produce;Ethnic Foods;Spices and Seasonings',
          image: 'ginger.png',
          consistency: 'solid',
          name: 'fresh ginger',
          nameClean: 'ginger',
          original: '1 tablespoon fresh ginger, grated',
          originalName: 'fresh ginger, grated',
          amount: 1,
          unit: 'tablespoon',
          meta: ['fresh', 'grated'],
          measures: {
            us: {
              amount: 1,
              unitShort: 'Tbsp',
              unitLong: 'Tbsp',
            },
            metric: {
              amount: 1,
              unitShort: 'Tbsp',
              unitLong: 'Tbsp',
            },
          },
        },
        {
          id: 19335,
          aisle: 'Baking',
          image: 'sugar-in-bowl.png',
          consistency: 'solid',
          name: 'sugar',
          nameClean: 'sugar',
          original: '2 tablespoons sugar',
          originalName: 'sugar',
          amount: 2,
          unit: 'tablespoons',
          meta: [],
          measures: {
            us: {
              amount: 2,
              unitShort: 'Tbsps',
              unitLong: 'Tbsps',
            },
            metric: {
              amount: 2,
              unitShort: 'Tbsps',
              unitLong: 'Tbsps',
            },
          },
        },
        {
          id: 1002046,
          aisle: 'Condiments',
          image: 'dijon-mustard.jpg',
          consistency: 'liquid',
          name: 'dijon mustard',
          nameClean: 'creole mustard',
          original: '1 teaspoon Dijon mustard',
          originalName: 'Dijon mustard',
          amount: 1,
          unit: 'teaspoon',
          meta: [],
          measures: {
            us: {
              amount: 1,
              unitShort: 'tsp',
              unitLong: 'teaspoon',
            },
            metric: {
              amount: 1,
              unitShort: 'tsp',
              unitLong: 'teaspoon',
            },
          },
        },
        {
          id: 4582,
          aisle: 'Oil, Vinegar, Salad Dressing',
          image: 'vegetable-oil.jpg',
          consistency: 'liquid',
          name: 'canola oil',
          nameClean: 'cooking oil',
          original: '1/2 cup canola oil',
          originalName: 'canola oil',
          amount: 0.5,
          unit: 'cup',
          meta: [],
          measures: {
            us: {
              amount: 0.5,
              unitShort: 'cups',
              unitLong: 'cups',
            },
            metric: {
              amount: 118.294,
              unitShort: 'ml',
              unitLong: 'milliliters',
            },
          },
        },
        {
          id: 11165,
          aisle: 'Produce;Spices and Seasonings',
          image: 'cilantro.png',
          consistency: 'solid',
          name: 'cilantro',
          nameClean: 'cilantro',
          original: '1 tablespoon chopped cilantro',
          originalName: 'chopped cilantro',
          amount: 1,
          unit: 'tablespoon',
          meta: ['chopped'],
          measures: {
            us: {
              amount: 1,
              unitShort: 'Tbsp',
              unitLong: 'Tbsp',
            },
            metric: {
              amount: 1,
              unitShort: 'Tbsp',
              unitLong: 'Tbsp',
            },
          },
        },
        {
          id: 1009159,
          aisle: 'Produce',
          image: 'zest-lime.jpg',
          consistency: 'solid',
          name: 'lime zest',
          nameClean: 'lime peel',
          original: '1/2 teaspoon finely grated lime zest',
          originalName: 'finely grated lime zest',
          amount: 0.5,
          unit: 'teaspoon',
          meta: ['finely grated'],
          measures: {
            us: {
              amount: 0.5,
              unitShort: 'tsps',
              unitLong: 'teaspoons',
            },
            metric: {
              amount: 0.5,
              unitShort: 'tsps',
              unitLong: 'teaspoons',
            },
          },
        },
        {
          id: 10011819,
          aisle: 'Produce;Ethnic Foods',
          image: 'habanero-pepper.jpg',
          consistency: 'solid',
          name: 'habanero chile',
          nameClean: 'habanero chili',
          original: '1 Scotch bonnet or habanero chile, seeded & diced',
          originalName: 'Scotch bonnet or habanero chile, seeded & diced',
          amount: 1,
          unit: '',
          meta: ['diced', 'seeded'],
          measures: {
            us: {
              amount: 1,
              unitShort: '',
              unitLong: '',
            },
            metric: {
              amount: 1,
              unitShort: '',
              unitLong: '',
            },
          },
        },
        {
          id: 10011282,
          aisle: 'Produce',
          image: 'red-onion.png',
          consistency: 'solid',
          name: 'red onion',
          nameClean: 'red onion',
          original: '1/4 cup thinly sliced red onion',
          originalName: 'thinly sliced red onion',
          amount: 0.25,
          unit: 'cup',
          meta: ['red', 'thinly sliced'],
          measures: {
            us: {
              amount: 0.25,
              unitShort: 'cups',
              unitLong: 'cups',
            },
            metric: {
              amount: 59.147,
              unitShort: 'ml',
              unitLong: 'milliliters',
            },
          },
        },
        {
          id: 1102047,
          aisle: 'Spices and Seasonings',
          image: 'salt-and-pepper.jpg',
          consistency: 'solid',
          name: 'salt and pepper',
          nameClean: 'salt and pepper',
          original: 'Salt and freshly ground black pepper',
          originalName: 'Salt and freshly ground black pepper',
          amount: 1,
          unit: 'serving',
          meta: ['black', 'freshly ground'],
          measures: {
            us: {
              amount: 1,
              unitShort: 'serving',
              unitLong: 'serving',
            },
            metric: {
              amount: 1,
              unitShort: 'serving',
              unitLong: 'serving',
            },
          },
        },
      ],
      id: 637797,
      title: 'Avocado-Mango Salad With Grilled Shrimp',
      readyInMinutes: 45,
      servings: 4,
      sourceUrl:
        'https://www.foodista.com/recipe/NSTFKPHS/avocado-mango-salad-with-grilled-shrimp',
      image: 'https://spoonacular.com/recipeImages/633171-556x370.jpg',
      imageType: 'jpg',
      summary:
        'Avocado-Mango Salad With Grilled Shrimp is a <b>gluten free, dairy free, and pescatarian</b> main course. One portion of this dish contains around <b>49g of protein</b>, <b>46g of fat</b>, and a total of <b>732 calories</b>. For <b>$6.36 per serving</b>, this recipe <b>covers 36%</b> of your daily requirements of vitamins and minerals. This recipe serves 4. From preparation to the plate, this recipe takes around <b>around 45 minutes</b>. If you have , hass avocados, lime zest, and a few other ingredients on hand, you can make it. <b>The Fourth Of July</b> will be even more special with this recipe. This recipe is liked by 5 foodies and cooks. It is brought to you by Foodista. Taking all factors into account, this recipe <b>earns a spoonacular score of 74%</b>, which is solid. Similar recipes are <a href="https://spoonacular.com/recipes/mango-avocado-and-grilled-shrimp-salad-with-a-peanut-dressing-249037">Mango, Avocado and Grilled Shrimp Salad with a Peanut Dressing</a>, <a href="https://spoonacular.com/recipes/grilled-shrimp-tacos-with-mango-avocado-salsa-610210">Grilled Shrimp Tacos with Mango Avocado Salsa</a>, and <a href="https://spoonacular.com/recipes/grilled-jerk-shrimp-tacos-with-mango-and-avocado-salsa-708004">Grilled Jerk Shrimp Tacos with Mango and Avocado Salsa</a>.',
      cuisines: [],
      dishTypes: [
        'side dish',
        'lunch',
        'salad',
        'main course',
        'main dish',
        'dinner',
      ],
      diets: ['gluten free', 'dairy free', 'pescatarian'],
      occasions: ["father's day", '4th of july', 'summer'],
      instructions:
        'Preheat gas grill to high.\nMake the dressing: Combine all dressing ingredients (except oil) in a blender and blend until smooth. While blender is running, remove lid and pour in oil in a steady stream. Continue blending for several seconds, then remove and set aside.\nPrepare the shrimp: Rinse shrimp and pat dry with a papertowel. Add about 1/3 cup of dressing and toss to coat. Let sit for 15 to 20 minutes. String onto wooden or metal skewars for grilling. Grill over high heat for about 2 to 3 minutes per side. Remove from grill, let cool, them remove from skewars.\nIn a large bowl, combine mango, avocado and grilled shrimp. Add dressing to taste; toss lightly and serve.',
      analyzedInstructions: [
        {
          name: '',
          steps: [
            {
              number: 1,
              step: 'Preheat gas grill to high.',
              ingredients: [],
              equipment: [
                {
                  id: 404706,
                  name: 'grill',
                  localizedName: 'grill',
                  image: 'grill.jpg',
                },
              ],
            },
          ],
        },
        {
          name: 'Make the dressing',
          steps: [
            {
              number: 1,
              step: 'Combine all dressing ingredients (except oil) in a blender and blend until smooth. While blender is running, remove lid and pour in oil in a steady stream. Continue blending for several seconds, then remove and set aside.',
              ingredients: [
                {
                  id: 4582,
                  name: 'cooking oil',
                  localizedName: 'cooking oil',
                  image: 'vegetable-oil.jpg',
                },
              ],
              equipment: [
                {
                  id: 404726,
                  name: 'blender',
                  localizedName: 'blender',
                  image: 'blender.png',
                },
              ],
            },
            {
              number: 2,
              step: 'Prepare the shrimp: Rinse shrimp and pat dry with a papertowel.',
              ingredients: [
                {
                  id: 15270,
                  name: 'shrimp',
                  localizedName: 'shrimp',
                  image: 'shrimp.png',
                },
              ],
              equipment: [],
            },
            {
              number: 3,
              step: 'Add about 1/3 cup of dressing and toss to coat.',
              ingredients: [],
              equipment: [],
            },
            {
              number: 4,
              step: 'Let sit for 15 to 20 minutes. String onto wooden or metal skewars for grilling. Grill over high heat for about 2 to 3 minutes per side.',
              ingredients: [],
              equipment: [
                {
                  id: 404706,
                  name: 'grill',
                  localizedName: 'grill',
                  image: 'grill.jpg',
                },
              ],
              length: {
                number: 17,
                unit: 'minutes',
              },
            },
            {
              number: 5,
              step: 'Remove from grill, let cool, them remove from skewars.',
              ingredients: [],
              equipment: [
                {
                  id: 404706,
                  name: 'grill',
                  localizedName: 'grill',
                  image: 'grill.jpg',
                },
              ],
            },
            {
              number: 6,
              step: 'In a large bowl, combine mango, avocado and grilled shrimp.',
              ingredients: [
                {
                  id: 0,
                  name: 'grilled shrimp',
                  localizedName: 'grilled shrimp',
                  image: 'shrimp.png',
                },
                {
                  id: 9037,
                  name: 'avocado',
                  localizedName: 'avocado',
                  image: 'avocado.jpg',
                },
                {
                  id: 9176,
                  name: 'mango',
                  localizedName: 'mango',
                  image: 'mango.jpg',
                },
              ],
              equipment: [
                {
                  id: 404783,
                  name: 'bowl',
                  localizedName: 'bowl',
                  image: 'bowl.jpg',
                },
              ],
            },
            {
              number: 7,
              step: 'Add dressing to taste; toss lightly and serve.',
              ingredients: [],
              equipment: [],
            },
          ],
        },
      ],
      originalId: null,
      spoonacularSourceUrl:
        'https://spoonacular.com/avocado-mango-salad-with-grilled-shrimp-633171',
    },
    {
      vegetarian: false,
      vegan: false,
      glutenFree: true,
      dairyFree: true,
      veryHealthy: false,
      cheap: false,
      veryPopular: false,
      sustainable: false,
      weightWatcherSmartPoints: 17,
      gaps: 'no',
      lowFodmap: false,
      aggregateLikes: 6,
      spoonacularScore: 74,
      healthScore: 31,
      creditsText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
      license: 'CC BY 3.0',
      sourceName: 'Foodista',
      pricePerServing: 636.03,
      extendedIngredients: [
        {
          id: 15270,
          aisle: 'Seafood',
          image: 'shrimp.png',
          consistency: 'solid',
          name: 'shrimp',
          nameClean: 'shrimp',
          original: '2 pounds large shrimp, shelled and deveined',
          originalName: 'shrimp, shelled and deveined',
          amount: 2,
          unit: 'pounds',
          meta: ['shelled', 'deveined'],
          measures: {
            us: {
              amount: 2,
              unitShort: 'lb',
              unitLong: 'pounds',
            },
            metric: {
              amount: 907.185,
              unitShort: 'g',
              unitLong: 'grams',
            },
          },
        },
        {
          id: 9037,
          aisle: 'Produce',
          image: 'avocado.jpg',
          consistency: 'solid',
          name: 'hass avocados',
          nameClean: 'avocado',
          original: '2 Hass avocados, pitted, peeled & cubed',
          originalName: 'Hass avocados, pitted, peeled & cubed',
          amount: 2,
          unit: '',
          meta: ['pitted', 'cubed', 'peeled'],
          measures: {
            us: {
              amount: 2,
              unitShort: '',
              unitLong: '',
            },
            metric: {
              amount: 2,
              unitShort: '',
              unitLong: '',
            },
          },
        },
        {
          id: 9176,
          aisle: 'Produce',
          image: 'mango.jpg',
          consistency: 'solid',
          name: 'mango',
          nameClean: 'mango',
          original: '1 mango, peeled and diced',
          originalName: 'mango, peeled and diced',
          amount: 1,
          unit: '',
          meta: ['diced', 'peeled'],
          measures: {
            us: {
              amount: 1,
              unitShort: '',
              unitLong: '',
            },
            metric: {
              amount: 1,
              unitShort: '',
              unitLong: '',
            },
          },
        },
        {
          id: 1029159,
          aisle: 'Produce',
          image: 'lime-wedge.jpg',
          consistency: 'solid',
          name: 'lime wedges',
          nameClean: 'lime wedge',
          original: 'Lime wedges, for serving',
          originalName: 'Lime wedges, for serving',
          amount: 1,
          unit: 'serving',
          meta: ['for serving'],
          measures: {
            us: {
              amount: 1,
              unitShort: 'serving',
              unitLong: 'serving',
            },
            metric: {
              amount: 1,
              unitShort: 'serving',
              unitLong: 'serving',
            },
          },
        },
        {
          id: 9176,
          aisle: 'Produce',
          image: 'mango.jpg',
          consistency: 'solid',
          name: 'mango',
          nameClean: 'mango',
          original: '1 mango, peeled and finely diced (1 1/2 cups)',
          originalName: 'mango, peeled and finely diced',
          amount: 1.5,
          unit: 'cups',
          meta: ['diced', 'peeled', 'finely'],
          measures: {
            us: {
              amount: 1.5,
              unitShort: 'cups',
              unitLong: 'cups',
            },
            metric: {
              amount: 354.882,
              unitShort: 'ml',
              unitLong: 'milliliters',
            },
          },
        },
        {
          id: 1022068,
          aisle: 'Oil, Vinegar, Salad Dressing',
          image: 'red-wine-vinegar.jpg',
          consistency: 'liquid',
          name: 'red wine vinegar',
          nameClean: 'red wine vinegar',
          original: '1/4 cup red wine vinegar',
          originalName: 'red wine vinegar',
          amount: 0.25,
          unit: 'cup',
          meta: ['red'],
          measures: {
            us: {
              amount: 0.25,
              unitShort: 'cups',
              unitLong: 'cups',
            },
            metric: {
              amount: 59.147,
              unitShort: 'ml',
              unitLong: 'milliliters',
            },
          },
        },
        {
          id: 9160,
          aisle: 'Produce',
          image: 'lime-juice.png',
          consistency: 'liquid',
          name: 'lime juice',
          nameClean: 'lime juice',
          original: '2 tablespoons fresh lime juice',
          originalName: 'fresh lime juice',
          amount: 2,
          unit: 'tablespoons',
          meta: ['fresh'],
          measures: {
            us: {
              amount: 2,
              unitShort: 'Tbsps',
              unitLong: 'Tbsps',
            },
            metric: {
              amount: 2,
              unitShort: 'Tbsps',
              unitLong: 'Tbsps',
            },
          },
        },
        {
          id: 11216,
          aisle: 'Produce;Ethnic Foods;Spices and Seasonings',
          image: 'ginger.png',
          consistency: 'solid',
          name: 'fresh ginger',
          nameClean: 'ginger',
          original: '1 tablespoon fresh ginger, grated',
          originalName: 'fresh ginger, grated',
          amount: 1,
          unit: 'tablespoon',
          meta: ['fresh', 'grated'],
          measures: {
            us: {
              amount: 1,
              unitShort: 'Tbsp',
              unitLong: 'Tbsp',
            },
            metric: {
              amount: 1,
              unitShort: 'Tbsp',
              unitLong: 'Tbsp',
            },
          },
        },
        {
          id: 19335,
          aisle: 'Baking',
          image: 'sugar-in-bowl.png',
          consistency: 'solid',
          name: 'sugar',
          nameClean: 'sugar',
          original: '2 tablespoons sugar',
          originalName: 'sugar',
          amount: 2,
          unit: 'tablespoons',
          meta: [],
          measures: {
            us: {
              amount: 2,
              unitShort: 'Tbsps',
              unitLong: 'Tbsps',
            },
            metric: {
              amount: 2,
              unitShort: 'Tbsps',
              unitLong: 'Tbsps',
            },
          },
        },
        {
          id: 1002046,
          aisle: 'Condiments',
          image: 'dijon-mustard.jpg',
          consistency: 'liquid',
          name: 'dijon mustard',
          nameClean: 'creole mustard',
          original: '1 teaspoon Dijon mustard',
          originalName: 'Dijon mustard',
          amount: 1,
          unit: 'teaspoon',
          meta: [],
          measures: {
            us: {
              amount: 1,
              unitShort: 'tsp',
              unitLong: 'teaspoon',
            },
            metric: {
              amount: 1,
              unitShort: 'tsp',
              unitLong: 'teaspoon',
            },
          },
        },
        {
          id: 4582,
          aisle: 'Oil, Vinegar, Salad Dressing',
          image: 'vegetable-oil.jpg',
          consistency: 'liquid',
          name: 'canola oil',
          nameClean: 'cooking oil',
          original: '1/2 cup canola oil',
          originalName: 'canola oil',
          amount: 0.5,
          unit: 'cup',
          meta: [],
          measures: {
            us: {
              amount: 0.5,
              unitShort: 'cups',
              unitLong: 'cups',
            },
            metric: {
              amount: 118.294,
              unitShort: 'ml',
              unitLong: 'milliliters',
            },
          },
        },
        {
          id: 11165,
          aisle: 'Produce;Spices and Seasonings',
          image: 'cilantro.png',
          consistency: 'solid',
          name: 'cilantro',
          nameClean: 'cilantro',
          original: '1 tablespoon chopped cilantro',
          originalName: 'chopped cilantro',
          amount: 1,
          unit: 'tablespoon',
          meta: ['chopped'],
          measures: {
            us: {
              amount: 1,
              unitShort: 'Tbsp',
              unitLong: 'Tbsp',
            },
            metric: {
              amount: 1,
              unitShort: 'Tbsp',
              unitLong: 'Tbsp',
            },
          },
        },
        {
          id: 1009159,
          aisle: 'Produce',
          image: 'zest-lime.jpg',
          consistency: 'solid',
          name: 'lime zest',
          nameClean: 'lime peel',
          original: '1/2 teaspoon finely grated lime zest',
          originalName: 'finely grated lime zest',
          amount: 0.5,
          unit: 'teaspoon',
          meta: ['finely grated'],
          measures: {
            us: {
              amount: 0.5,
              unitShort: 'tsps',
              unitLong: 'teaspoons',
            },
            metric: {
              amount: 0.5,
              unitShort: 'tsps',
              unitLong: 'teaspoons',
            },
          },
        },
        {
          id: 10011819,
          aisle: 'Produce;Ethnic Foods',
          image: 'habanero-pepper.jpg',
          consistency: 'solid',
          name: 'habanero chile',
          nameClean: 'habanero chili',
          original: '1 Scotch bonnet or habanero chile, seeded & diced',
          originalName: 'Scotch bonnet or habanero chile, seeded & diced',
          amount: 1,
          unit: '',
          meta: ['diced', 'seeded'],
          measures: {
            us: {
              amount: 1,
              unitShort: '',
              unitLong: '',
            },
            metric: {
              amount: 1,
              unitShort: '',
              unitLong: '',
            },
          },
        },
        {
          id: 10011282,
          aisle: 'Produce',
          image: 'red-onion.png',
          consistency: 'solid',
          name: 'red onion',
          nameClean: 'red onion',
          original: '1/4 cup thinly sliced red onion',
          originalName: 'thinly sliced red onion',
          amount: 0.25,
          unit: 'cup',
          meta: ['red', 'thinly sliced'],
          measures: {
            us: {
              amount: 0.25,
              unitShort: 'cups',
              unitLong: 'cups',
            },
            metric: {
              amount: 59.147,
              unitShort: 'ml',
              unitLong: 'milliliters',
            },
          },
        },
        {
          id: 1102047,
          aisle: 'Spices and Seasonings',
          image: 'salt-and-pepper.jpg',
          consistency: 'solid',
          name: 'salt and pepper',
          nameClean: 'salt and pepper',
          original: 'Salt and freshly ground black pepper',
          originalName: 'Salt and freshly ground black pepper',
          amount: 1,
          unit: 'serving',
          meta: ['black', 'freshly ground'],
          measures: {
            us: {
              amount: 1,
              unitShort: 'serving',
              unitLong: 'serving',
            },
            metric: {
              amount: 1,
              unitShort: 'serving',
              unitLong: 'serving',
            },
          },
        },
      ],
      id: 633172,
      title: 'Avocado-Mango Salad With Grilled Shrimp',
      readyInMinutes: 45,
      servings: 4,
      sourceUrl:
        'https://www.foodista.com/recipe/NSTFKPHS/avocado-mango-salad-with-grilled-shrimp',
      image: 'https://spoonacular.com/recipeImages/633171-556x370.jpg',
      imageType: 'jpg',
      summary:
        'Avocado-Mango Salad With Grilled Shrimp is a <b>gluten free, dairy free, and pescatarian</b> main course. One portion of this dish contains around <b>49g of protein</b>, <b>46g of fat</b>, and a total of <b>732 calories</b>. For <b>$6.36 per serving</b>, this recipe <b>covers 36%</b> of your daily requirements of vitamins and minerals. This recipe serves 4. From preparation to the plate, this recipe takes around <b>around 45 minutes</b>. If you have , hass avocados, lime zest, and a few other ingredients on hand, you can make it. <b>The Fourth Of July</b> will be even more special with this recipe. This recipe is liked by 5 foodies and cooks. It is brought to you by Foodista. Taking all factors into account, this recipe <b>earns a spoonacular score of 74%</b>, which is solid. Similar recipes are <a href="https://spoonacular.com/recipes/mango-avocado-and-grilled-shrimp-salad-with-a-peanut-dressing-249037">Mango, Avocado and Grilled Shrimp Salad with a Peanut Dressing</a>, <a href="https://spoonacular.com/recipes/grilled-shrimp-tacos-with-mango-avocado-salsa-610210">Grilled Shrimp Tacos with Mango Avocado Salsa</a>, and <a href="https://spoonacular.com/recipes/grilled-jerk-shrimp-tacos-with-mango-and-avocado-salsa-708004">Grilled Jerk Shrimp Tacos with Mango and Avocado Salsa</a>.',
      cuisines: [],
      dishTypes: [
        'side dish',
        'lunch',
        'salad',
        'main course',
        'main dish',
        'dinner',
      ],
      diets: ['gluten free', 'dairy free', 'pescatarian'],
      occasions: ["father's day", '4th of july', 'summer'],
      instructions:
        'Preheat gas grill to high.\nMake the dressing: Combine all dressing ingredients (except oil) in a blender and blend until smooth. While blender is running, remove lid and pour in oil in a steady stream. Continue blending for several seconds, then remove and set aside.\nPrepare the shrimp: Rinse shrimp and pat dry with a papertowel. Add about 1/3 cup of dressing and toss to coat. Let sit for 15 to 20 minutes. String onto wooden or metal skewars for grilling. Grill over high heat for about 2 to 3 minutes per side. Remove from grill, let cool, them remove from skewars.\nIn a large bowl, combine mango, avocado and grilled shrimp. Add dressing to taste; toss lightly and serve.',
      analyzedInstructions: [
        {
          name: '',
          steps: [
            {
              number: 1,
              step: 'Preheat gas grill to high.',
              ingredients: [],
              equipment: [
                {
                  id: 404706,
                  name: 'grill',
                  localizedName: 'grill',
                  image: 'grill.jpg',
                },
              ],
            },
          ],
        },
        {
          name: 'Make the dressing',
          steps: [
            {
              number: 1,
              step: 'Combine all dressing ingredients (except oil) in a blender and blend until smooth. While blender is running, remove lid and pour in oil in a steady stream. Continue blending for several seconds, then remove and set aside.',
              ingredients: [
                {
                  id: 4582,
                  name: 'cooking oil',
                  localizedName: 'cooking oil',
                  image: 'vegetable-oil.jpg',
                },
              ],
              equipment: [
                {
                  id: 404726,
                  name: 'blender',
                  localizedName: 'blender',
                  image: 'blender.png',
                },
              ],
            },
            {
              number: 2,
              step: 'Prepare the shrimp: Rinse shrimp and pat dry with a papertowel.',
              ingredients: [
                {
                  id: 15270,
                  name: 'shrimp',
                  localizedName: 'shrimp',
                  image: 'shrimp.png',
                },
              ],
              equipment: [],
            },
            {
              number: 3,
              step: 'Add about 1/3 cup of dressing and toss to coat.',
              ingredients: [],
              equipment: [],
            },
            {
              number: 4,
              step: 'Let sit for 15 to 20 minutes. String onto wooden or metal skewars for grilling. Grill over high heat for about 2 to 3 minutes per side.',
              ingredients: [],
              equipment: [
                {
                  id: 404706,
                  name: 'grill',
                  localizedName: 'grill',
                  image: 'grill.jpg',
                },
              ],
              length: {
                number: 17,
                unit: 'minutes',
              },
            },
            {
              number: 5,
              step: 'Remove from grill, let cool, them remove from skewars.',
              ingredients: [],
              equipment: [
                {
                  id: 404706,
                  name: 'grill',
                  localizedName: 'grill',
                  image: 'grill.jpg',
                },
              ],
            },
            {
              number: 6,
              step: 'In a large bowl, combine mango, avocado and grilled shrimp.',
              ingredients: [
                {
                  id: 0,
                  name: 'grilled shrimp',
                  localizedName: 'grilled shrimp',
                  image: 'shrimp.png',
                },
                {
                  id: 9037,
                  name: 'avocado',
                  localizedName: 'avocado',
                  image: 'avocado.jpg',
                },
                {
                  id: 9176,
                  name: 'mango',
                  localizedName: 'mango',
                  image: 'mango.jpg',
                },
              ],
              equipment: [
                {
                  id: 404783,
                  name: 'bowl',
                  localizedName: 'bowl',
                  image: 'bowl.jpg',
                },
              ],
            },
            {
              number: 7,
              step: 'Add dressing to taste; toss lightly and serve.',
              ingredients: [],
              equipment: [],
            },
          ],
        },
      ],
      originalId: null,
      spoonacularSourceUrl:
        'https://spoonacular.com/avocado-mango-salad-with-grilled-shrimp-633171',
    },
    {
      vegetarian: false,
      vegan: false,
      glutenFree: true,
      dairyFree: true,
      veryHealthy: false,
      cheap: false,
      veryPopular: false,
      sustainable: false,
      weightWatcherSmartPoints: 17,
      gaps: 'no',
      lowFodmap: false,
      aggregateLikes: 6,
      spoonacularScore: 74,
      healthScore: 31,
      creditsText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
      license: 'CC BY 3.0',
      sourceName: 'Foodista',
      pricePerServing: 636.03,
      extendedIngredients: [
        {
          id: 15270,
          aisle: 'Seafood',
          image: 'shrimp.png',
          consistency: 'solid',
          name: 'shrimp',
          nameClean: 'shrimp',
          original: '2 pounds large shrimp, shelled and deveined',
          originalName: 'shrimp, shelled and deveined',
          amount: 2,
          unit: 'pounds',
          meta: ['shelled', 'deveined'],
          measures: {
            us: {
              amount: 2,
              unitShort: 'lb',
              unitLong: 'pounds',
            },
            metric: {
              amount: 907.185,
              unitShort: 'g',
              unitLong: 'grams',
            },
          },
        },
        {
          id: 9037,
          aisle: 'Produce',
          image: 'avocado.jpg',
          consistency: 'solid',
          name: 'hass avocados',
          nameClean: 'avocado',
          original: '2 Hass avocados, pitted, peeled & cubed',
          originalName: 'Hass avocados, pitted, peeled & cubed',
          amount: 2,
          unit: '',
          meta: ['pitted', 'cubed', 'peeled'],
          measures: {
            us: {
              amount: 2,
              unitShort: '',
              unitLong: '',
            },
            metric: {
              amount: 2,
              unitShort: '',
              unitLong: '',
            },
          },
        },
        {
          id: 9176,
          aisle: 'Produce',
          image: 'mango.jpg',
          consistency: 'solid',
          name: 'mango',
          nameClean: 'mango',
          original: '1 mango, peeled and diced',
          originalName: 'mango, peeled and diced',
          amount: 1,
          unit: '',
          meta: ['diced', 'peeled'],
          measures: {
            us: {
              amount: 1,
              unitShort: '',
              unitLong: '',
            },
            metric: {
              amount: 1,
              unitShort: '',
              unitLong: '',
            },
          },
        },
        {
          id: 1029159,
          aisle: 'Produce',
          image: 'lime-wedge.jpg',
          consistency: 'solid',
          name: 'lime wedges',
          nameClean: 'lime wedge',
          original: 'Lime wedges, for serving',
          originalName: 'Lime wedges, for serving',
          amount: 1,
          unit: 'serving',
          meta: ['for serving'],
          measures: {
            us: {
              amount: 1,
              unitShort: 'serving',
              unitLong: 'serving',
            },
            metric: {
              amount: 1,
              unitShort: 'serving',
              unitLong: 'serving',
            },
          },
        },
        {
          id: 9176,
          aisle: 'Produce',
          image: 'mango.jpg',
          consistency: 'solid',
          name: 'mango',
          nameClean: 'mango',
          original: '1 mango, peeled and finely diced (1 1/2 cups)',
          originalName: 'mango, peeled and finely diced',
          amount: 1.5,
          unit: 'cups',
          meta: ['diced', 'peeled', 'finely'],
          measures: {
            us: {
              amount: 1.5,
              unitShort: 'cups',
              unitLong: 'cups',
            },
            metric: {
              amount: 354.882,
              unitShort: 'ml',
              unitLong: 'milliliters',
            },
          },
        },
        {
          id: 1022068,
          aisle: 'Oil, Vinegar, Salad Dressing',
          image: 'red-wine-vinegar.jpg',
          consistency: 'liquid',
          name: 'red wine vinegar',
          nameClean: 'red wine vinegar',
          original: '1/4 cup red wine vinegar',
          originalName: 'red wine vinegar',
          amount: 0.25,
          unit: 'cup',
          meta: ['red'],
          measures: {
            us: {
              amount: 0.25,
              unitShort: 'cups',
              unitLong: 'cups',
            },
            metric: {
              amount: 59.147,
              unitShort: 'ml',
              unitLong: 'milliliters',
            },
          },
        },
        {
          id: 9160,
          aisle: 'Produce',
          image: 'lime-juice.png',
          consistency: 'liquid',
          name: 'lime juice',
          nameClean: 'lime juice',
          original: '2 tablespoons fresh lime juice',
          originalName: 'fresh lime juice',
          amount: 2,
          unit: 'tablespoons',
          meta: ['fresh'],
          measures: {
            us: {
              amount: 2,
              unitShort: 'Tbsps',
              unitLong: 'Tbsps',
            },
            metric: {
              amount: 2,
              unitShort: 'Tbsps',
              unitLong: 'Tbsps',
            },
          },
        },
        {
          id: 11216,
          aisle: 'Produce;Ethnic Foods;Spices and Seasonings',
          image: 'ginger.png',
          consistency: 'solid',
          name: 'fresh ginger',
          nameClean: 'ginger',
          original: '1 tablespoon fresh ginger, grated',
          originalName: 'fresh ginger, grated',
          amount: 1,
          unit: 'tablespoon',
          meta: ['fresh', 'grated'],
          measures: {
            us: {
              amount: 1,
              unitShort: 'Tbsp',
              unitLong: 'Tbsp',
            },
            metric: {
              amount: 1,
              unitShort: 'Tbsp',
              unitLong: 'Tbsp',
            },
          },
        },
        {
          id: 19335,
          aisle: 'Baking',
          image: 'sugar-in-bowl.png',
          consistency: 'solid',
          name: 'sugar',
          nameClean: 'sugar',
          original: '2 tablespoons sugar',
          originalName: 'sugar',
          amount: 2,
          unit: 'tablespoons',
          meta: [],
          measures: {
            us: {
              amount: 2,
              unitShort: 'Tbsps',
              unitLong: 'Tbsps',
            },
            metric: {
              amount: 2,
              unitShort: 'Tbsps',
              unitLong: 'Tbsps',
            },
          },
        },
        {
          id: 1002046,
          aisle: 'Condiments',
          image: 'dijon-mustard.jpg',
          consistency: 'liquid',
          name: 'dijon mustard',
          nameClean: 'creole mustard',
          original: '1 teaspoon Dijon mustard',
          originalName: 'Dijon mustard',
          amount: 1,
          unit: 'teaspoon',
          meta: [],
          measures: {
            us: {
              amount: 1,
              unitShort: 'tsp',
              unitLong: 'teaspoon',
            },
            metric: {
              amount: 1,
              unitShort: 'tsp',
              unitLong: 'teaspoon',
            },
          },
        },
        {
          id: 4582,
          aisle: 'Oil, Vinegar, Salad Dressing',
          image: 'vegetable-oil.jpg',
          consistency: 'liquid',
          name: 'canola oil',
          nameClean: 'cooking oil',
          original: '1/2 cup canola oil',
          originalName: 'canola oil',
          amount: 0.5,
          unit: 'cup',
          meta: [],
          measures: {
            us: {
              amount: 0.5,
              unitShort: 'cups',
              unitLong: 'cups',
            },
            metric: {
              amount: 118.294,
              unitShort: 'ml',
              unitLong: 'milliliters',
            },
          },
        },
        {
          id: 11165,
          aisle: 'Produce;Spices and Seasonings',
          image: 'cilantro.png',
          consistency: 'solid',
          name: 'cilantro',
          nameClean: 'cilantro',
          original: '1 tablespoon chopped cilantro',
          originalName: 'chopped cilantro',
          amount: 1,
          unit: 'tablespoon',
          meta: ['chopped'],
          measures: {
            us: {
              amount: 1,
              unitShort: 'Tbsp',
              unitLong: 'Tbsp',
            },
            metric: {
              amount: 1,
              unitShort: 'Tbsp',
              unitLong: 'Tbsp',
            },
          },
        },
        {
          id: 1009159,
          aisle: 'Produce',
          image: 'zest-lime.jpg',
          consistency: 'solid',
          name: 'lime zest',
          nameClean: 'lime peel',
          original: '1/2 teaspoon finely grated lime zest',
          originalName: 'finely grated lime zest',
          amount: 0.5,
          unit: 'teaspoon',
          meta: ['finely grated'],
          measures: {
            us: {
              amount: 0.5,
              unitShort: 'tsps',
              unitLong: 'teaspoons',
            },
            metric: {
              amount: 0.5,
              unitShort: 'tsps',
              unitLong: 'teaspoons',
            },
          },
        },
        {
          id: 10011819,
          aisle: 'Produce;Ethnic Foods',
          image: 'habanero-pepper.jpg',
          consistency: 'solid',
          name: 'habanero chile',
          nameClean: 'habanero chili',
          original: '1 Scotch bonnet or habanero chile, seeded & diced',
          originalName: 'Scotch bonnet or habanero chile, seeded & diced',
          amount: 1,
          unit: '',
          meta: ['diced', 'seeded'],
          measures: {
            us: {
              amount: 1,
              unitShort: '',
              unitLong: '',
            },
            metric: {
              amount: 1,
              unitShort: '',
              unitLong: '',
            },
          },
        },
        {
          id: 10011282,
          aisle: 'Produce',
          image: 'red-onion.png',
          consistency: 'solid',
          name: 'red onion',
          nameClean: 'red onion',
          original: '1/4 cup thinly sliced red onion',
          originalName: 'thinly sliced red onion',
          amount: 0.25,
          unit: 'cup',
          meta: ['red', 'thinly sliced'],
          measures: {
            us: {
              amount: 0.25,
              unitShort: 'cups',
              unitLong: 'cups',
            },
            metric: {
              amount: 59.147,
              unitShort: 'ml',
              unitLong: 'milliliters',
            },
          },
        },
        {
          id: 1102047,
          aisle: 'Spices and Seasonings',
          image: 'salt-and-pepper.jpg',
          consistency: 'solid',
          name: 'salt and pepper',
          nameClean: 'salt and pepper',
          original: 'Salt and freshly ground black pepper',
          originalName: 'Salt and freshly ground black pepper',
          amount: 1,
          unit: 'serving',
          meta: ['black', 'freshly ground'],
          measures: {
            us: {
              amount: 1,
              unitShort: 'serving',
              unitLong: 'serving',
            },
            metric: {
              amount: 1,
              unitShort: 'serving',
              unitLong: 'serving',
            },
          },
        },
      ],
      id: 633173,
      title: 'Avocado-Mango Salad With Grilled Shrimp',
      readyInMinutes: 45,
      servings: 4,
      sourceUrl:
        'https://www.foodista.com/recipe/NSTFKPHS/avocado-mango-salad-with-grilled-shrimp',
      image: 'https://spoonacular.com/recipeImages/633171-556x370.jpg',
      imageType: 'jpg',
      summary:
        'Avocado-Mango Salad With Grilled Shrimp is a <b>gluten free, dairy free, and pescatarian</b> main course. One portion of this dish contains around <b>49g of protein</b>, <b>46g of fat</b>, and a total of <b>732 calories</b>. For <b>$6.36 per serving</b>, this recipe <b>covers 36%</b> of your daily requirements of vitamins and minerals. This recipe serves 4. From preparation to the plate, this recipe takes around <b>around 45 minutes</b>. If you have , hass avocados, lime zest, and a few other ingredients on hand, you can make it. <b>The Fourth Of July</b> will be even more special with this recipe. This recipe is liked by 5 foodies and cooks. It is brought to you by Foodista. Taking all factors into account, this recipe <b>earns a spoonacular score of 74%</b>, which is solid. Similar recipes are <a href="https://spoonacular.com/recipes/mango-avocado-and-grilled-shrimp-salad-with-a-peanut-dressing-249037">Mango, Avocado and Grilled Shrimp Salad with a Peanut Dressing</a>, <a href="https://spoonacular.com/recipes/grilled-shrimp-tacos-with-mango-avocado-salsa-610210">Grilled Shrimp Tacos with Mango Avocado Salsa</a>, and <a href="https://spoonacular.com/recipes/grilled-jerk-shrimp-tacos-with-mango-and-avocado-salsa-708004">Grilled Jerk Shrimp Tacos with Mango and Avocado Salsa</a>.',
      cuisines: [],
      dishTypes: [
        'side dish',
        'lunch',
        'salad',
        'main course',
        'main dish',
        'dinner',
      ],
      diets: ['gluten free', 'dairy free', 'pescatarian'],
      occasions: ["father's day", '4th of july', 'summer'],
      instructions:
        'Preheat gas grill to high.\nMake the dressing: Combine all dressing ingredients (except oil) in a blender and blend until smooth. While blender is running, remove lid and pour in oil in a steady stream. Continue blending for several seconds, then remove and set aside.\nPrepare the shrimp: Rinse shrimp and pat dry with a papertowel. Add about 1/3 cup of dressing and toss to coat. Let sit for 15 to 20 minutes. String onto wooden or metal skewars for grilling. Grill over high heat for about 2 to 3 minutes per side. Remove from grill, let cool, them remove from skewars.\nIn a large bowl, combine mango, avocado and grilled shrimp. Add dressing to taste; toss lightly and serve.',
      analyzedInstructions: [
        {
          name: '',
          steps: [
            {
              number: 1,
              step: 'Preheat gas grill to high.',
              ingredients: [],
              equipment: [
                {
                  id: 404706,
                  name: 'grill',
                  localizedName: 'grill',
                  image: 'grill.jpg',
                },
              ],
            },
          ],
        },
        {
          name: 'Make the dressing',
          steps: [
            {
              number: 1,
              step: 'Combine all dressing ingredients (except oil) in a blender and blend until smooth. While blender is running, remove lid and pour in oil in a steady stream. Continue blending for several seconds, then remove and set aside.',
              ingredients: [
                {
                  id: 4582,
                  name: 'cooking oil',
                  localizedName: 'cooking oil',
                  image: 'vegetable-oil.jpg',
                },
              ],
              equipment: [
                {
                  id: 404726,
                  name: 'blender',
                  localizedName: 'blender',
                  image: 'blender.png',
                },
              ],
            },
            {
              number: 2,
              step: 'Prepare the shrimp: Rinse shrimp and pat dry with a papertowel.',
              ingredients: [
                {
                  id: 15270,
                  name: 'shrimp',
                  localizedName: 'shrimp',
                  image: 'shrimp.png',
                },
              ],
              equipment: [],
            },
            {
              number: 3,
              step: 'Add about 1/3 cup of dressing and toss to coat.',
              ingredients: [],
              equipment: [],
            },
            {
              number: 4,
              step: 'Let sit for 15 to 20 minutes. String onto wooden or metal skewars for grilling. Grill over high heat for about 2 to 3 minutes per side.',
              ingredients: [],
              equipment: [
                {
                  id: 404706,
                  name: 'grill',
                  localizedName: 'grill',
                  image: 'grill.jpg',
                },
              ],
              length: {
                number: 17,
                unit: 'minutes',
              },
            },
            {
              number: 5,
              step: 'Remove from grill, let cool, them remove from skewars.',
              ingredients: [],
              equipment: [
                {
                  id: 404706,
                  name: 'grill',
                  localizedName: 'grill',
                  image: 'grill.jpg',
                },
              ],
            },
            {
              number: 6,
              step: 'In a large bowl, combine mango, avocado and grilled shrimp.',
              ingredients: [
                {
                  id: 0,
                  name: 'grilled shrimp',
                  localizedName: 'grilled shrimp',
                  image: 'shrimp.png',
                },
                {
                  id: 9037,
                  name: 'avocado',
                  localizedName: 'avocado',
                  image: 'avocado.jpg',
                },
                {
                  id: 9176,
                  name: 'mango',
                  localizedName: 'mango',
                  image: 'mango.jpg',
                },
              ],
              equipment: [
                {
                  id: 404783,
                  name: 'bowl',
                  localizedName: 'bowl',
                  image: 'bowl.jpg',
                },
              ],
            },
            {
              number: 7,
              step: 'Add dressing to taste; toss lightly and serve.',
              ingredients: [],
              equipment: [],
            },
          ],
        },
      ],
      originalId: null,
      spoonacularSourceUrl:
        'https://spoonacular.com/avocado-mango-salad-with-grilled-shrimp-633171',
    },
  ];

